use_frameworks!

platform :ios, '9.0'

target 'JudyPlusButtonTabBar_Example' do
  pod 'JudyPlusButtonTabBar', :path => '../'

  target 'JudyPlusButtonTabBar_Tests' do
    inherit! :search_paths

    
  end
end
